version: "3"

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker-junk/docker-db:/var/lib/postgresql/data
    networks:
      - webnet
    ports:
      - '5434:5432'

  redis:
    image: redis
    ports:
      - '6380:6379'
    volumes:
      - ./docker-junk/api-redis:/data
    networks:
      - webnet

  api:

#   To build the dockerfile from the image uncomment the image key above and comment the build below
    build:
      context: ./
      dockerfile: docker-dev/Dockerfile

    ports:
      - "80:7000"
    networks:
      - webnet
    depends_on:
      - db
      - redis
    volumes:
      - .:/docker-junk/api-data
    environment:
      DATABASE_URI: postgres://postgres:password@db:5432/db_name
      REDIS_SERVER_URL: redis://redis:6379/0

networks:
  webnet:

