version: 2 # use CircleCI 2.0

orbs:
  codecov: codecov/codecov@1.0.2

docker_setup: &docker_setup
  docker: # run the steps with Docker
    # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
    - image: circleci/python:3.7.2
      environment: # environment variables for primary container
        PIPENV_VENV_IN_PROJECT: true
        TEST_DATABASE_URL: "postgresql://utility-user:password@localhost:5432/util_db"
        APP_SECRET_KEY: $SECRET_KEY
        CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
        PG_HOST: localhost
        PG_USER: utility-user
    - image: circleci/postgres
      environment:
        POSTGRES_USER: utility-user
        POSTGRES_DB: util_db
        POSTGRES_PASSWORD: password


    # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/

#commands:
#  upload_test_coverage_to_cov:
#    description: "Upload test coverage"
#    steps:
#      - codecov/upload:
#          file: coverage.xml

restore_cache: &run_restore_cache
  restore_cache:
    # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
    key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

install_dependencies: &install_dependencies
  name: Install Pipenv Dependencies
  command: |
    sudo pip install pipenv
    pipenv install

save_cache: &save_cache # cache Python dependencies using checksum of Pipfile as the cache-key
    key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
    paths:
      - ".venv"
      - "/usr/local/bin"

run_tests: &run_tests
  name: Run tests
  command: |
    mkdir -p dumped_files && pipenv run pytest

generate_coverage_report: &generate_coverage_report
  name: 'Upload coverage report'
  command:
    codecov/upload:
      file: coverage.xml


jobs: # A basic unit of work in a run
  build:
    <<: *docker_setup
    working_directory: ~/repo
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          name: Basic Setup
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - *run_restore_cache
      - run: *install_dependencies
      - save_cache: *save_cache

  run_test_and_upload_coverage:
    <<: *docker_setup
    working_directory: ~/repo-test-dir
    steps:
      - checkout
      - run:
          name: Basic Setup
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - *run_restore_cache
      - run: *install_dependencies
      - run: *run_tests
      - save_cache: *save_cache
      - run:
          name: Upload Coverage
          command: |
            bash <(curl -s https://codecov.io/bash)

  deploy:
    <<: *docker_setup
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Heroku and Login
          command: |
            env >> .env
            # install heroku CLI
            curl https://cli-assets.heroku.com/install.sh | sh
            # login to heroku docker registry
            heroku container:login
            # Login to heroku registry
            echo $HEROKU_API_KEY | docker login --username=$HEROKU_USERNAME --password-stdin registry.heroku.com

      - run:
          name: Build Dockerfile
          command: |
            docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f docker-heroku/Dockerfile .
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
      - run:
          name: Deploy to heroku
          command: |
            heroku container:release web --app $HEROKU_APP_NAME

workflows:
  version: 2
  run_test_and_send_coverage:
      jobs:
        - run_test_and_upload_coverage
        - deploy:
            requires:
              - run_test_and_upload_coverage
            filters:
              branches:
                only:
                  - staging


