from .basic_auth import Register
from .reset_password import ForgotPassword
from .organisation import CreateOrg
from .unit import UnitView
from .parameter import ParameterView
from .profile import Profile
from .invitation import OrgInvitations
from .roles import OrgRoleView
from .appliaance_category import ApplianceCategoryView
from .appliance import ApplianceView
from .logs import LogsView
from .reports import ReportsView
