"""empty message

Revision ID: 128d0dd37c81
Revises: b2dd9f3a5b91
Create Date: 2019-09-10 12:04:15.540501

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '128d0dd37c81'
down_revision = 'b2dd9f3a5b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User',
                    'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=21),
                    existing_server_default=sa.text(
                        'nextval(\'"User_id_seq"\'::regclass)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User',
                    'id',
                    existing_type=sa.String(length=21),
                    type_=sa.INTEGER(),
                    existing_server_default=sa.text(
                        'nextval(\'"User_id_seq"\'::regclass)'))
    # ### end Alembic commands ###
