"""Added unique constraint to formula

Revision ID: 1412d2979e4b
Revises: 4b6358ba3783
Create Date: 2020-06-09 17:04:26.060950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1412d2979e4b'
down_revision = '4b6358ba3783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Formula', sa.Column('unit_id', sa.String(length=21), nullable=True))
    op.create_unique_constraint('org_formula_unique_constraint', 'Formula', ['name', 'organisation_id'])
    op.create_foreign_key('unit_id_fk', 'Formula', 'Unit', ['unit_id'], ['id'], ondelete='CASCADE')
    op.alter_column('LogValue', 'numeric_value',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('FormulaToken', 'constant',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unit_id_fk', 'Formula', type_='foreignkey')
    op.drop_constraint('org_formula_unique_constraint', 'Formula', type_='unique')
    op.drop_column('Formula', 'unit_id')
    op.alter_column('LogValue', 'numeric_value',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('FormulaToken', 'constant',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=True)
    # ### end Alembic commands ###
