"""Create ApplianceCategory model

Revision ID: 2c813a2c060e
Revises: a57eab4c7be5
Create Date: 2020-02-20 16:01:56.644021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c813a2c060e'
down_revision = 'a57eab4c7be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ApplianceCategory',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(length=21), nullable=True),
    sa.Column('updated_by_id', sa.String(length=21), nullable=True),
    sa.Column('organisation_id', sa.String(length=21), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['Organisation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organisation_id', name='app_category_org_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ApplianceCategory')
    # ### end Alembic commands ###
