"""empty message

Revision ID: 397d7d58fe1c
Revises: 8c2040cb395f
Create Date: 2019-10-21 16:27:47.308690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397d7d58fe1c'
down_revision = '8c2040cb395f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Unit',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'symbol', name='unit_name_and_symbol_unique_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Unit')
    # ### end Alembic commands ###
