"""Added username and updated unique constraints

Revision ID: 3a47273c9a43
Revises: 4889bb8c5a74
Create Date: 2019-09-23 14:19:25.208141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a47273c9a43'
down_revision = '4889bb8c5a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(length=20), nullable=False))
    op.create_unique_constraint('username_unique_constraint', 'User', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('username_unique_constraint', 'User', type_='unique')
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
