"""Change logvalue table

Revision ID: 46d31ba106f7
Revises: 9f650010f9fa
Create Date: 2020-05-07 14:09:32.513607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d31ba106f7'
down_revision = '9f650010f9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LogValue', sa.Column('numeric_value', sa.Float(precision=2), nullable=True))
    op.alter_column('LogValue', 'value', new_column_name='text_value', nullable=True)
    op.execute("""
            UPDATE "LogValue" as lg
                SET numeric_value = lg.text_value::FLOAT, text_value = NULL
            WHERE lg.id IN (
                SELECT lg2.id FROM "LogValue" as lg2
                JOIN "Parameter" 
                    ON "Parameter".id = lg2.parameter_id
            
            );
       """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE "LogValue" as lg
            SET  text_value = lg.numeric_value, numeric_value = NULL
        WHERE lg.id IN (
            SELECT lg2.id FROM "LogValue" as lg2
            JOIN "Parameter" 
                ON "Parameter".id = lg2.parameter_id
        
        );
    """)
    op.alter_column('LogValue', 'text_value', new_column_name='value', nullable=True)
    op.drop_column('LogValue', 'numeric_value')
    # ### end Alembic commands ###
