"""empty message

Revision ID: 62561735c912
Revises: 3a47273c9a43
Create Date: 2019-09-23 17:52:06.063049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62561735c912'
down_revision = '3a47273c9a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('org_email_unique_constraint', 'Organisation', ['email'])
    op.create_unique_constraint('org_unique_name_constraint', 'Organisation', ['name'])
    op.drop_constraint('Organisation_email_key', 'Organisation', type_='unique')
    op.drop_constraint('Organisation_name_key', 'Organisation', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Organisation_name_key', 'Organisation', ['name'])
    op.create_unique_constraint('Organisation_email_key', 'Organisation', ['email'])
    op.drop_constraint('org_unique_name_constraint', 'Organisation', type_='unique')
    op.drop_constraint('org_email_unique_constraint', 'Organisation', type_='unique')
    # ### end Alembic commands ###
