"""Create appliance

Revision ID: 6975f1526c46
Revises: 2c813a2c060e
Create Date: 2020-02-27 16:41:36.600440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6975f1526c46'
down_revision = '2c813a2c060e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Appliance',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('appliance_category_id', sa.String(length=21), nullable=True),
    sa.Column('created_by_id', sa.String(length=21), nullable=True),
    sa.Column('updated_by_id', sa.String(length=21), nullable=True),
    sa.Column('organisation_id', sa.String(length=21), nullable=False),
    sa.ForeignKeyConstraint(['appliance_category_id'], ['ApplianceCategory.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['Organisation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label', 'organisation_id', 'appliance_category_id', name='org_appliance_constraint')
    )
    op.create_table('ApplianceParameter',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('appliance_id', sa.String(length=21), nullable=True),
    sa.Column('parameter_id', sa.String(length=21), nullable=False),
    sa.Column('organisation_id', sa.String(length=21), nullable=False),
    sa.Column('created_by_id', sa.String(length=21), nullable=True),
    sa.Column('updated_by_id', sa.String(length=21), nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['Appliance.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['Organisation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parameter_id'], ['Parameter.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appliance_id', 'parameter_id', 'organisation_id', name='appliance_parameter_unique_indx')
    )
    op.alter_column('ApplianceCategory', 'organisation_id',
               existing_type=sa.VARCHAR(length=21),
               nullable=False)
    op.drop_column('Parameter', 'required')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Parameter', sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('ApplianceCategory', 'organisation_id',
               existing_type=sa.VARCHAR(length=21),
               nullable=True)
    op.drop_table('ApplianceParameter')
    op.drop_table('Appliance')
    # ### end Alembic commands ###
