"""Make unit work well when org_id is null

Revision ID: 8ae48170fa1d
Revises: 6975f1526c46
Create Date: 2020-03-17 09:35:12.698255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae48170fa1d'
down_revision = '6975f1526c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unit_name_and_greek_symbol_when_org_is_null', 'Unit', ['name', 'greek_symbol_num'], unique=True, postgresql_where=sa.text('organisation_id IS NULL'))
    op.create_index('unit_name_and_letter_when_org_is_null', 'Unit', ['name', 'letter_symbol'], unique=True, postgresql_where=sa.text('organisation_id IS NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unit_name_and_letter_when_org_is_null', table_name='Unit')
    op.drop_index('unit_name_and_greek_symbol_when_org_is_null', table_name='Unit')
    # ### end Alembic commands ###
