"""Improve organisation model by adding creator_id and some other fields

Revision ID: 8c2040cb395f
Revises: 62561735c912
Create Date: 2019-10-18 20:52:36.941708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2040cb395f'
down_revision = '62561735c912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organisation', sa.Column('creator_id', sa.String(length=21), nullable=False))
    op.add_column('Organisation', sa.Column('image_public_id', sa.Text(), nullable=True))
    op.add_column('Organisation', sa.Column('image_url', sa.Text(), nullable=True))
    op.create_unique_constraint('org_unique_website_constraint', 'Organisation', ['website'])
    op.drop_constraint('org_email_unique_constraint', 'Organisation', type_='unique')
    op.drop_constraint('org_unique_name_constraint', 'Organisation', type_='unique')
    op.create_foreign_key(None, 'Organisation', 'User', ['creator_id'], ['id'])
    op.drop_column('Organisation', 'email')
    op.drop_column('Organisation', 'password_hash')
    op.drop_column('Organisation', 'logo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organisation', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Organisation', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Organisation', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Organisation', type_='foreignkey')
    op.create_unique_constraint('org_unique_name_constraint', 'Organisation', ['name'])
    op.create_unique_constraint('org_email_unique_constraint', 'Organisation', ['email'])
    op.drop_constraint('org_unique_website_constraint', 'Organisation', type_='unique')
    op.drop_column('Organisation', 'image_url')
    op.drop_column('Organisation', 'image_public_id')
    op.drop_column('Organisation', 'creator_id')
    # ### end Alembic commands ###
