"""Generating reports models...

Revision ID: 9f650010f9fa
Revises: fc88d420cf41
Create Date: 2020-05-06 09:20:51.390919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f650010f9fa'
down_revision = 'fc88d420cf41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Report',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('organisation_id', sa.String(length=21), nullable=False),
    sa.Column('created_by_id', sa.String(length=21), nullable=False),
    sa.Column('updated_by_id', sa.String(length=21), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['Organisation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReportSection',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('appliance_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['appliance_id'], ['Appliance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['Report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReportColumn',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_section_id', sa.String(), nullable=False),
    sa.Column('formula_id', sa.String(), nullable=True),
    sa.Column('parameter_id', sa.String(length=22), nullable=True),
    sa.Column('aggregation_type', sa.Enum('SUMMATION', 'AVERAGE', 'MINIMUM', 'MAXIMUM', name='aggregation_type_enum'), nullable=False),
    sa.Column('aggregate_by_column', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['Parameter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_section_id'], ['ReportSection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReportColumn')
    op.drop_table('ReportSection')
    op.drop_table('Report')
    op.execute('DROP TYPE aggregation_type_enum')
    # ### end Alembic commands ###
