"""Updated Unit model to have greek_symbol_num and letter_symbol

Revision ID: a703a747118c
Revises: 397d7d58fe1c
Create Date: 2019-10-23 12:33:56.078914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a703a747118c'
down_revision = '397d7d58fe1c'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Unit', sa.Column('greek_symbol_num', sa.SmallInteger(), nullable=True))
    op.drop_constraint('unit_name_and_symbol_unique_constraint', 'Unit', type_='unique')
    op.alter_column('Unit', 'symbol', new_column_name='letter_symbol', nullable=True)
    op.create_unique_constraint('unit_name_and_greeksymbolnum_unique_constraint', 'Unit', ['name', 'greek_symbol_num'])
    op.create_unique_constraint('unit_name_and_letter_symbol_unique_constraint', 'Unit', ['name', 'letter_symbol'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Unit', 'letter_symbol', new_column_name='symbol', nullable=False)
    op.create_unique_constraint('unit_name_and_symbol_unique_constraint', 'Unit', ['name', 'symbol'])
    op.drop_constraint('unit_name_and_letter_symbol_unique_constraint', 'Unit', type_='unique')
    op.drop_constraint('unit_name_and_greeksymbolnum_unique_constraint', 'Unit', type_='unique')
    op.drop_column('Unit', 'greek_symbol_num')
    # ### end Alembic commands ###
