"""empty message

Revision ID: b1803102d111
Revises: 65b9741ff2b3
Create Date: 2020-01-06 10:30:49.404500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1803102d111'
down_revision = '65b9741ff2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('image_public_id', sa.Text(), nullable=True))
    op.add_column('User', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'image_url')
    op.drop_column('User', 'image_public_id')
    # ### end Alembic commands ###
