"""Created formula models

Revision ID: b518a58f7d6e
Revises: c1fcdbef301c
Create Date: 2020-06-08 13:05:03.605568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b518a58f7d6e'
down_revision = 'c1fcdbef301c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DateAggregator',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.Column('sql_func_call', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Formula',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('has_formula', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=21), nullable=True),
    sa.Column('updated_by_id', sa.String(length=21), nullable=True),
    sa.Column('organisation_id', sa.String(length=21), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['Organisation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FormulaToken',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CONSTANT', 'PARAMETER', 'SYMBOL', 'FORMULA', name='token_type_enum'), nullable=False),
    sa.Column('value_from', sa.Enum('PREV', 'CURRENT', name='token_value_from_enum'), nullable=False),
    sa.Column('parent_id', sa.String(length=21), nullable=False),
    sa.Column('formula_id', sa.String(length=21), nullable=True),
    sa.Column('parameter_id', sa.String(length=21), nullable=True),
    sa.Column('created_by_id', sa.String(length=21), nullable=True),
    sa.Column('updated_by_id', sa.String(length=21), nullable=True),
    sa.Column('organisation_id', sa.String(length=21), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['formula_id'], ['Formula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['Organisation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parameter_id'], ['Parameter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['Formula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('LogValue', 'numeric_value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('ReportColumn', 'parameter_id',
               existing_type=sa.VARCHAR(length=22),
               type_=sa.String(length=21),
               existing_nullable=True)
    op.create_foreign_key('report_column_formula_fk', 'ReportColumn', 'Formula', ['formula_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('report_column_formula_fk', 'ReportColumn', type_='foreignkey')
    op.alter_column('ReportColumn', 'parameter_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=22),
               existing_nullable=True)
    op.alter_column('LogValue', 'numeric_value',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_table('FormulaToken')
    op.drop_table('Formula')
    op.drop_table('DateAggregator')
    op.execute('DROP TYPE token_type_enum')
    op.execute('DROP TYPE token_value_from_enum')
    # ### end Alembic commands ###
