"""Add required field to appliance_parameter

Revision ID: c1fcdbef301c
Revises: 46d31ba106f7
Create Date: 2020-05-25 14:20:38.216359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1fcdbef301c'
down_revision = '46d31ba106f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ApplianceParameter', sa.Column('required', sa.Boolean(), nullable=True, default=False))
    op.execute('''
        UPDATE "ApplianceParameter"
            SET required = FALSE
            WHERE required IS NULL
    ''')
    op.alter_column('ApplianceParameter', 'required', nullable=False)
    op.alter_column('LogValue', 'numeric_value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('LogValue', 'numeric_value',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('ApplianceParameter', 'required')
    # ### end Alembic commands ###
