"""empty message

Revision ID: f5f1fbfd6198
Revises: 9227f4a42619
Create Date: 2020-01-16 00:22:20.853951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5f1fbfd6198'
down_revision = '9227f4a42619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Membership', sa.Column('role_id', sa.String(length=21), nullable=False))
    op.create_foreign_key(None, 'Membership', 'Role', ['role_id'], ['id'])
    op.drop_column('Membership', 'role')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS role')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TYPE role as ENUM('OWNER', 'ENGINEER', 'MANAGER', 'REGULAR_USER');
    """)
    op.add_column('Membership', sa.Column('role', postgresql.ENUM('OWNER', 'ENGINEER', 'MANAGER', 'REGULAR_USER', name='role'), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'Membership', type_='foreignkey')
    op.drop_column('Membership', 'role_id')
    # ### end Alembic commands ###
