"""Make appliance_id and parameter_id not nullable

Revision ID: fc88d420cf41
Revises: f293fdde82dd
Create Date: 2020-04-28 16:40:46.837842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc88d420cf41'
down_revision = 'f293fdde82dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Log', 'appliance_id',
               existing_type=sa.VARCHAR(length=21),
               nullable=False)
    op.alter_column('LogValue', 'log_id',
               existing_type=sa.VARCHAR(length=21),
               nullable=False)
    op.alter_column('LogValue', 'parameter_id',
               existing_type=sa.VARCHAR(length=21),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('LogValue', 'parameter_id',
               existing_type=sa.VARCHAR(length=21),
               nullable=True)
    op.alter_column('LogValue', 'log_id',
               existing_type=sa.VARCHAR(length=21),
               nullable=True)
    op.alter_column('Log', 'appliance_id',
               existing_type=sa.VARCHAR(length=21),
               nullable=True)
    # ### end Alembic commands ###
